on:
  push:
    branches:
      - master





jobs:
  builD:
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - name:  'Login to Ducker hub'
        run: docker login --username khalifa10081 --pasword dckr_pat_c5pNSKvCExHq9oUNB4-YhtkF0Dk